def main():
    test.fail('fail no test')
    pass